"""empty message

Revision ID: 9f2bc172aa15
Revises: 433323564826
Create Date: 2020-04-14 09:09:59.907522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f2bc172aa15'
down_revision = '433323564826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('gender', sa.String(), nullable=True))
    op.drop_column('people', 'catchphrase')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('catchphrase', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('people', 'gender')
    # ### end Alembic commands ###
